mysql_settings: &mysql_settings
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: spike_user
  password: pw123
  host: 127.0.0.1
  port: 53307

development:
  <<: *mysql_settings
  database: app-engine-ruby-spike-DEV

production:
  <<: *mysql_settings
  database: app-engine-ruby-spike-PROD

test:
  <<: *mysql_settings
  database: app-engine-ruby-spike-TEST
